web:
    build: .
    links:
     - mysql
    environment:
     - DB_NAME=wordpress
     - DB_USER=root
     - DB_PASSWORD=password
     - DB_HOST=mysql
    ports:
     - "8080:80"
    volumes:
     - ./wp/wp-content:/var/www/html/wp-content
mysql:
    image: mysql
    environment:
     - MYSQL_DATABASE=wordpress
     - MYSQL_ROOT_PASSWORD=password
    volumes:
     - ./data:/var/lib/mysql
